### ISSUE TITLE
FuseJS/05 - 디버깅, Uno/02 - 네이티브 API 사용하기

### ISSUE THREAD

**Issue by DesignOZ** [Hazealign/fuse-docs-kr#12]
시작합니다.

**Comment by Hazealign** [comment]
고생 많으셨습니다. 이번에 Fuse에서 Android에 V8 Javascript Engine을 적용하면서 FuseJS/05 문서가 많이 바뀔 것 같습니다. 일단 읽는 개발자들이 혼선이 없게끔 주석을 달아뒀습니다.

이 이슈는 닫도록 하겠습니다.
