### ISSUE TITLE
GraphicsTheme (그래픽스 테마) translation clarification

### ISSUE THREAD

**Issue by JustinaKim** [Hazealign/fuse-docs-kr#15]
GraphicsTheme (그래픽스 테마):

TextInput is a higher-level control and will by default not be rendered since it relies on native platform controls. Either define your own style for this or use a BasicTheme instead.

한글 번역: 
TextInput은 상위 레벨의 컴포넌트입니다. 기본적으로 각 플랫폼의 네이티브 컴포넌트를 바탕으로 렌더링됩니다.

여기 번역 부분 다시 확인 하실수있나요? 제가 잘못 이해할수도 있는데 여기 보면 기본적으로  not be rendered 인데 렌더링이 된다고 되있네요. 작은 부분이긴하지만 확인 부탁드려요.

**Comment by englekk** [comment]
기본적으로 네이티브 플랫폼 콘트롤에 의존하므로 렌더링 되지 않습니다.
=> 이게 직역인데요. 각 플랫폼의 네이티브 콘트롤을 사용한다는 의미라서 위와 같이 의역했습니다. 말씀하신대로 더 정확한 의미가 되려면 '기본적으로 네이티브 플랫폼의 콘트롤을 사용하므로 (Fuse 컨텍스트는) 렌더링하지 않습니다.' 이렇게 되겠네요.
